import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ForgotPassword(),
        ]),
      ),
    );
  }
}

class ForgotPassword extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          width: 331,
          height: 98,
          child: Text(
            'Forgot\npassword?',
            style: TextStyle(
              color: Colors.black,
              fontSize: 36,
              fontFamily: 'Montserrat',
              fontWeight: FontWeight.w700,
              height: 0.03,
            ),
          ),
        ),
      ],
    );
  }
}
